In [1]:
import pandas as pd
from pathlib import Path

# Auswertung alter Fotografien

In [2]:
input_data_folder = "../data/"
input_data_filename = "AAB_cleaned.csv"

In [3]:
data_file = Path(input_data_folder) / input_data_filename
df_cars = pd.read_csv(data_file, sep= "\t")  

# Variante für Google Colab
# df_cars = pd.read_csv( "https://raw.githubusercontent.com/SebastianZug/RoboLabVortraege/refs/heads/main/30_PythonAutomobile/project/data/AAB_cleaned.csv", sep= "\t")

In [4]:
df_cars.head()

,Seite,Familienname,Vorname,Kennzeichen,Nummer,Beruf_Stand,Wohnort,Adresse,Fzg_Typ,Kreis_Stadt,Firma,id,_Vorname,_Vorname_Adaption
0,103,Trautmann,Robert,S S,80,Privatmann,Arnstadt,Lindenallee 11,Lxw.,Arnstadt,-,17091280,Robert,False
1,420,Beckmann,Otto,I K,15,Molk.-Techniker,Breslau,N. Taschenstr. 25 a,KrR.,Provinz Schlesien,-,17101628,Otto,False
2,429,Barteczko,Karl,I K,439,Maschinist,Ratibor,Neuer Markt 5,KrR.,Provinz Schlesien,-,17101933,Karl,False
3,529,"Leesen, v.",-,I P,233,Ingenieur,St. Margarethen,-,KrR.,Schleswig-Holstein,-,17105384,-,False
4,2,-,-,A,73,-,Stadt Dessau,Franzstr. 30,LW.,Stadt Dessau,Berlin-Anh. Maschinenbau-Aktien-Gesellschaft,17088030,-,False

## Wie können wir die Daten von Fotografien auswerten?

https://vorkriegs-klassiker-rundschau.blog/dixi/

https://i0.wp.com/vorkriegs-klassiker-rundschau.blog/wp-content/uploads/2020/11/dux_vor_1910_bei_kaub_am_rhein_galerie1.jpg?ssl=1

In [5]:
df_cars.Kennzeichen.unique()

array(['S S', 'I K', 'I P', 'A', 'B', 'C G', 'H B', 'H H', 'H L', 'L',
       'M I', 'M II', 'O I', 'R J', 'S', 'R A', 'O III', 'V', 'IV', 'III',
       'II', 'I E', 'I H', 'I D', 'I C', 'I S', 'I T', 'I Z', 'II Z',
       'II U', 'II N', 'II S', 'II D', 'II E', 'II H', 'III A', 'II C',
       'VI C', 'VI B', 'VI A', 'V S', 'O II', 'I', 'S A', 'S L', 'S M',
       'S R', 'W', 'I A', 'I M', 'I L', 'I X', 'I Y', 'II A', 'II B',
       'Droschke', 'IV B', 'III P', 'III S', 'III T', 'III X', 'III Y',
       'III Z', 'III E', 'III H', 'III K', 'III M', 'III C', 'III D',
       'V O', 'V R'], dtype=object)

In [6]:
# Eleminiere die Lehrzeichen aus der Spalte Kennzeichen und fasse diesen string mit dem Inhalt der Spalte Nummer zusammen
df_cars["_Kennzeichen"] = df_cars["Kennzeichen"].str.replace(" ", "")
df_cars["_Kennzeichen"] = df_cars["_Kennzeichen"] + " " + df_cars["Nummer"]

df_cars.head()

,Seite,Familienname,Vorname,Kennzeichen,Nummer,Beruf_Stand,Wohnort,Adresse,Fzg_Typ,Kreis_Stadt,Firma,id,_Vorname,_Vorname_Adaption,_Kennzeichen
0,103,Trautmann,Robert,S S,80,Privatmann,Arnstadt,Lindenallee 11,Lxw.,Arnstadt,-,17091280,Robert,False,SS 80
1,420,Beckmann,Otto,I K,15,Molk.-Techniker,Breslau,N. Taschenstr. 25 a,KrR.,Provinz Schlesien,-,17101628,Otto,False,IK 15
2,429,Barteczko,Karl,I K,439,Maschinist,Ratibor,Neuer Markt 5,KrR.,Provinz Schlesien,-,17101933,Karl,False,IK 439
3,529,"Leesen, v.",-,I P,233,Ingenieur,St. Margarethen,-,KrR.,Schleswig-Holstein,-,17105384,-,False,IP 233
4,2,-,-,A,73,-,Stadt Dessau,Franzstr. 30,LW.,Stadt Dessau,Berlin-Anh. Maschinenbau-Aktien-Gesellschaft,17088030,-,False,A 73

In [7]:
df_cars[df_cars["_Kennzeichen"] == "CG 802"]

# https://vorkriegs-klassiker-rundschau.blog/dixi/
# Dixi Tourenwagen um 1909, Zulassung: Sachsen-Coburg-Gotha, aufgenommen am Rhein bei Kaub

,Seite,Familienname,Vorname,Kennzeichen,Nummer,Beruf_Stand,Wohnort,Adresse,Fzg_Typ,Kreis_Stadt,Firma,id,_Vorname,_Vorname_Adaption,_Kennzeichen
43431,23,Thiel,Heinrich,C G,802,Fabrikdirektor,Ruhla G. A.,-,Lxw.,L.R.A.B. Waltershausen,-,17088699,Heinrich,False,CG 802

In [8]:
df_cars[df_cars["_Kennzeichen"] == "IIIE 105"]

# https://vorkriegs-klassiker-rundschau.blog/bildergalerie-nach-marken-3/adler-automobile/
# https://i0.wp.com/vorkriegs-klassiker-rundschau.blog/wp-content/uploads/2016/01/adler_datiert_07-1907_galerie1.jpg?resize=584%2C744&ssl=1

,Seite,Familienname,Vorname,Kennzeichen,Nummer,Beruf_Stand,Wohnort,Adresse,Fzg_Typ,Kreis_Stadt,Firma,id,_Vorname,_Vorname_Adaption,_Kennzeichen
18815,1023,Schmierer,Paul,III E,105,Kaufmann,Feuerbach,-,GW.,OAB. Stuttgart Amt,-,17122026,Paul,False,IIIE 105

In [9]:
df_cars[df_cars["_Kennzeichen"] == "V 532"] 

# https://vorkriegs-klassiker-rundschau.blog/bildergalerie-nach-marken-3/adler-automobile/
# https://i0.wp.com/vorkriegs-klassiker-rundschau.blog/wp-content/uploads/2022/09/Adler_5-9-PS_Fam_Gnuechtel_Emaillefirma_via-Volker_Zimmer_Lauter_Erzgeb.-1.jpg?ssl=1

,Seite,Familienname,Vorname,Kennzeichen,Nummer,Beruf_Stand,Wohnort,Adresse,Fzg_Typ,Kreis_Stadt,Firma,id,_Vorname,_Vorname_Adaption,_Kennzeichen
25683,227,Gnüchtel,Gustav,V,532,Fabrikbesitzer,Lauter,-,KrW.,Kreishauptmanschaft Zwickau,-,17095158,Gustav,False,V 532

https://www.auto-motor-und-sport.de/event/125-jahre-automobil-1910-bis-1919-paradigmenwechsel-am-fliessband/

In [10]:
df_cars[df_cars["_Kennzeichen"] == "IIA 1243"]

,Seite,Familienname,Vorname,Kennzeichen,Nummer,Beruf_Stand,Wohnort,Adresse,Fzg_Typ,Kreis_Stadt,Firma,id,_Vorname,_Vorname_Adaption,_Kennzeichen
42863,871,Schmitt,Aug.,II A,1243,Schlosser,München,Parkstr. 32,Lxw.,Bayern,-,17117018,August,True,IIA 1243

In [12]:
df_cars[df_cars["_Kennzeichen"] == "IH 28"]

Empty DataFrame
Columns: [Seite, Familienname, Vorname, Kennzeichen, Nummer, Beruf_Stand, Wohnort, Adresse, Fzg_Typ, Kreis_Stadt, Firma, id, _Vorname, _Vorname_Adaption, _Kennzeichen]
Index: []